version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y -qq lftp

      - checkout
      - run: 
          name: Build website and deploy output via FTP
          command: |
            cd website
            npm install
            npm run build
            lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnv build/paynow-docs/ ./public_html --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
            lftp -c "set ftp:ssl-allow no; open -u $LIVE_USERNAME,$LIVE_PASSWORD $LIVE_HOST; mirror -Rnv build/paynow-docs/ ./public_html --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"            
